jobs:
  build_test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: TSLint
          command: npm run lint
      - run:
          name: Build
          command: ./node_modules/@angular/cli/bin/ng build --prod
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build_test:
    jobs:
      - build_test
